version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./wwebjs_auth:/app/wwebjs_auth
      - ./dados:/app/dados
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tsw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
